// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPyU3Q5naF3UOqn4ufY9d7nTD57meUCs',
    appId: '1:1080934717756:web:b7554106138931f21e6639',
    messagingSenderId: '1080934717756',
    projectId: 'cw6-mad-project1616',
    authDomain: 'cw6-mad-project1616.firebaseapp.com',
    storageBucket: 'cw6-mad-project1616.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36f7UnpVwN6TRc933tpGDfnq9djec2-E',
    appId: '1:1080934717756:android:871d9c899152cc821e6639',
    messagingSenderId: '1080934717756',
    projectId: 'cw6-mad-project1616',
    storageBucket: 'cw6-mad-project1616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiHW4G6QWEEtPAYR04UfYTBhqCjzMlGno',
    appId: '1:1080934717756:ios:9a663e2d766388421e6639',
    messagingSenderId: '1080934717756',
    projectId: 'cw6-mad-project1616',
    storageBucket: 'cw6-mad-project1616.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiHW4G6QWEEtPAYR04UfYTBhqCjzMlGno',
    appId: '1:1080934717756:ios:9a663e2d766388421e6639',
    messagingSenderId: '1080934717756',
    projectId: 'cw6-mad-project1616',
    storageBucket: 'cw6-mad-project1616.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPyU3Q5naF3UOqn4ufY9d7nTD57meUCs',
    appId: '1:1080934717756:web:df6f6355439fe41d1e6639',
    messagingSenderId: '1080934717756',
    projectId: 'cw6-mad-project1616',
    authDomain: 'cw6-mad-project1616.firebaseapp.com',
    storageBucket: 'cw6-mad-project1616.firebasestorage.app',
  );
}
